
---
title: "Visualizing spatial data in-class exercise"
output: pdf_document

---

<!-- 
# Source https://ggplot2-book.org/maps
-->

# Using maps

```{r setup}

library(scico)
library(maps)
library(stars)
library(magrittr) # pipes
library(lintr) # code linting
library(raster) # raster handling (needed for relief)
library(viridis) # viridis color scale
library(cowplot) # stack ggplots
library(tidyverse)
library(sf)
```

```{r worldmap, warning=FALSE}
library(rworldmap)

wmap <- rworldmap::getMap(resolution = "low")  %>%
  st_as_sf()

ggplot(data = wmap) +
  geom_sf(aes(fill = NAME)) +
  theme_minimal() +
  guides(fill = FALSE) # don't show legend

```

```{r}
wmap_ant <- getMap()[-which(getMap()$ADMIN=='Antarctica'),]  %>%
  st_as_sf()
ggplot(data = wmap_ant) +
  geom_sf(aes(fill = NAME)) +
  theme_minimal() +
  guides(fill = FALSE) # don't show legend

```




```{r il-county}
il_counties <- map_data("county", "illinois") 
head(il_counties)
```

```{r map-il}
ggplot(il_counties, aes(long, lat)) + 
  geom_point(size = .25, show.legend = FALSE) +
  coord_quickmap()

ggplot(il_counties, aes(long, lat, group = group)) +
  geom_polygon(fill = "white", colour = "grey50") + 
  coord_quickmap()
```


```{r, message = FALSE}

il_county <- tigris::counties(state = "illinois", cb = TRUE) %>%
    st_as_sf() 
ggplot(il_county) + 
  geom_sf(color = "blue", fill = "gray") 
```


## Add cities
*Data source: https://geo-csv.com/illinois/*

```{r}
illinois <- read_csv("data/illinois.csv")
ggplot(il_county) + 
  geom_sf(color = "blue", fill = "gray") +
 geom_point(data = illinois, 
            aes(x = city_longitude, y = city_latitude), 
            colour = "darkblue", size = 0.1, alpha = 0.4) + 
  coord_sf()

```

# Raster maps
## Simple example: https://ggplot2.tidyverse.org/reference/ggsf.html

```{r}
nc <- sf::st_read(system.file("shape/nc.shp", package = "sf"), quiet = TRUE)
ggplot(nc) +
  geom_sf(aes(fill = AREA))

# If not supplied, coord_sf() will take the CRS from the first layer
# and automatically transform all other layers to use that CRS. This
# ensures that all data will correctly line up
nc_3857 <- sf::st_transform(nc, 3857)
ggplot() +
  geom_sf(data = nc) +
  geom_sf(data = nc_3857, colour = "red", fill = NA)

# Unfortunately if you plot other types of feature you'll need to use
# show.legend to tell ggplot2 what type of legend to use
nc_3857$mid <- sf::st_centroid(nc_3857$geometry)
ggplot(nc_3857) +
  geom_sf(colour = "white") +
  geom_sf(aes(geometry = mid, size = AREA), show.legend = "point")

# You can also use layers with x and y aesthetics. To have these interpreted
# as longitude/latitude you need to set the default CRS in coord_sf()
ggplot(nc_3857) +
  geom_sf() +
  annotate("point", x = -80, y = 35, colour = "red", size = 4) +
  coord_sf(default_crs = sf::st_crs(4326))

# To add labels, use geom_sf_label().
ggplot(nc_3857[1:3, ]) +
   geom_sf(aes(fill = AREA)) +
   geom_sf_label(aes(label = NAME))

```

## Spain
*source: https://github.com/aaumaitre/maps_Spain*



<!--
## Switzerland
*Source: https://timogrossenbacher.ch/bivariate-maps-with-ggplot2-and-sf/* and *https://timogrossenbacher.ch/bivariate-maps-with-ggplot2-and-sf/*
```{r}
# read cantonal borders
canton_geo <- read_sf("data/input/g2k15.shp")

# read country borders
country_geo <- read_sf("data/input/g2l15.shp")

# read lakes
lake_geo <- read_sf("data/input/g2s15.shp")

# read productive area (2324 municipalities)
municipality_prod_geo <- read_sf("data/input/gde-1-1-15.shp")

# read in raster of relief
relief <- raster("data/input/02-relief-ascii.asc") %>%
  # hide relief outside of Switzerland by masking with country borders
  mask(country_geo) %>%
  as("SpatialPixelsDataFrame") %>%
  as.data.frame() %>%
  rename(value = `X02.relief.ascii`)

# clean up
rm(country_geo)
```

```{r}

ggplot() +
    # raster comes as the first layer, municipalities on top
    geom_raster(
      data = relief, aes(
        x = x, 
        y = y, 
        alpha = value
        )
      ) +
    # use the "alpha hack"
    scale_alpha(name = "", range = c(0.6, 0), guide = FALSE)  + 
    # municipality polygons
    geom_polygon(
      data = map_data, aes(
        fill = brks, 
        x = long, 
        y = lat, 
        group = group
        )
      ) +
    # municipality outline
    geom_path(
      data = map_data, aes(
        x = long, 
        y = lat, 
        group = group
        ), 
      color = "white",
      linewidth = 0.1
      ) +
    # apart from that, nothing changes
    coord_equal() +
    theme_map() +
    theme(
      legend.position = "bottom",
      plot.title = element_text(hjust = 0.5),
      plot.subtitle = element_text(hjust = 0.5)
      ) +
    labs(
      x = NULL, 
      y = NULL, 
      title = "Switzerland's regional demographics", 
      subtitle = "Average age in Swiss municipalities, 2015", 
      caption = "Geometries: ThemaKart, BFS; Data: BFS, 2016; Relief: swisstopo, 2016"
      ) + 
    scale_fill_manual(
      values = rev(scico(8, palette = "davos")[2:7]),
      #breaks = rev(brks_scale),
      name = "Average age",
      drop = FALSE,
      #labels = labels_scale,
      guide = guide_legend(
        direction = "horizontal",
        keyheight = unit(2, units = "mm"), 
        keywidth = unit(70/length(labels), units = "mm"),
        title.position = 'top',
        title.hjust = 0.5,
        label.hjust = 1,
        nrow = 1,
        byrow = TRUE,
        reverse = TRUE,
        label.position = "bottom"
      )
    )
```
-->
