---
title: "Introduction to computing for the social sciences"
date: 2023-06-12T12:25:00-05:00
publishDate: 2019-03-01T12:25:00-05:00
draft: false

aliases: ["/cm001.html", "/syllabus/introduction-to-computing-for-the-social-sciences/"]

# Talk start and end times.
#   End time can optionally be hidden by prefixing the line with `#`.
#time_end: 2022-08-22T14:20:00-05:00
all_day: false

# Authors. Comma separated list, e.g. `["Bob Smith", "David Jones"]`.
authors: []

# Abstract and optional shortened version.
abstract: ""
summary: "Overview of programming and reproducible research, applications to social sciences, and course logistics."

# Location of event.
#location: [via zoom](https://applications.zoom.us/lti/rich/home/meeting/detail)

# Is this a selected talk? (true/false)
selected: false

# Tags (optional).
#   Set `tags: []` for no tags, or use the form `tags: ["A Tag", "Another Tag"]` for one or more tags.
tags: []

# Links (optional).
url_pdf: ""
url_slides: "/slides/introduction-to-computing-for-information-science/"
url_video: ""
url_code: ""

# Does the content use math formatting?
math: false
---



## Overview

* Introduction to the course
* Identify major course objectives
* Identify course logistics and expectations
* Familiarize with basic principles of programming and reproducible workflow
* Software setup instructions

## Before class

* Read the "Welcome" page and chapter 1 "Introduction" in [R for Data Science](http://r4ds.had.co.nz/). (*Note that there is a new draft we'll be moving to soon: [Second Edition of R for Data Science](https://r4ds.hadley.nz/)*)

## Class materials

* [Introduction to computing for the social sciences](/notes/intro-to-course/)
* [Good Enough Practices in Scientific Computing](http://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1005510). Additional resource and good summary of best computing practices

## What you need to do after class

* Read the [Setup](/setup/) section and install the required software
* Fill out [this survey](https://docs.google.com/forms/d/e/1FAIpQLSfV_g4z7rpNWz_ONmH1oLrItXprHjo8-KBpnd19FbEJDCrEDA/viewform?usp=sf_link)
* Explore this website
