---
title: "Assignment 4"
date: 2025-02-13T13:30:00-06:00  # Schedule page publish date
publishDate: 2019-03-01T12:25:00-05:00
draft: false

summary: "Tableau Dashboard"
---

```{r setup, include = FALSE}
knitr::opts_chunk$set()
```

# Assignment 4: Tableau dashboard
For this assignment, you need to make and publish an interactive dashboard using the SSA name data.

You need at least two tabs, one that is temporally focused and one that focuses upon a different aspect (for example, name gender). 

Within each tab, you need clear labeling and explanations, interactivity, and a mixture of graphics and tables, as appropriate (e.g. you cannot have only one graph, or only one graph type). 

This needs to allow readers to answer a particular question. 




## Can I use different data?

YES! If you have another dataset around which you want to build an interactive visualization, go ahead! Just check in with us before you proceed.

## Grading

Your visualization will be evaluated using the following criteria:

* Is it truthful?
* Is it functional?
* Is it beautiful?
* Is it insightful?
* Is it enlightening?

In addition to the visualization and accompanying narrative, write an approximately 500 word explanation defending your design choices. This includes (but is not limited to):

* What is the story?
* Why did you select this graphical form?
* What is the role of interactivity? How does it enhance your ability to tell the story and communicate the data?

## Submission details

Submit your visualization and analysis, including a link to your Tableau site and a PDF to ensure we have access in case something goes awry. Include your design explanation within the document (you can include an additional tab, if needed). Note that expectations remain the same regarding an explanation of your data, organization, etc. 

