---
title: "Final Proposal"
date: 2026-03-04T13:30:00-06:00  # Schedule page publish date
publishDate: 2019-03-01T12:25:00-05:00
draft: false

summary: "Final project proposal"
---


### Overview
This is a proposal for your final project. The final project needs to contain either a website and/or interactive element and needs to be of sufficient scope to provide insight about your topic of choice. If you aren't sure about how to expand the scope, please check in! You can post on Ed and/or attend office hours. 

 

For this -- you can do either a website or a github repo. In either of these, you will want to incorporate plotly and/or shiny. 

 

See the final assignment for more details: https://macs40700.netlify.app/assignments/final-project/Links to an external site.

 

For this, you will want to give us a minimum of three graphs and a maximum of five. All graphs should be essential for understanding your research question of interest, well-designed, polished, and clear to an outside reader. There will be an accompanying writeup that has two components: a discussion of the findings in the graphs and an assessment of the overall design. The write up should be approximately 500-700 words. 

